#! /bin/bash
#
# Author: Bartosz Zawadka, 2016
#
# Contact: kontakt@bartoszzawadka.pl
#
# /etc/init.d/pi-sensor-service
#
### BEGIN INIT INFO
# Provides: pi-sensor-service
# Required-Start: $remote_fs $syslog $network
# Required-Stop: $remote_fs $syslog $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Raspberry Pi DHT2X sensors service daemon
# Descirption: Raspberry Pi DHT2X sensors service daemon
### END INIT INFO

PIDFILE=/var/run/pi-sensor-service.pid
USER=root
CHUID=root
STARTAS=/usr/bin/python
ARGS=/usr/local/lib/python2.7/dist-packages/pi-sensor-service/service.pyc
RTIME=10

case "$1" in
	start)
		echo "Starting service"
		sudo start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --user $USER --chuid $CHUID --background --startas $STARTAS -- $ARGS
		;;
	stop)
		echo "Stopping service"
		sudo start-stop-daemon --stop --pidfile $PIDFILE --retry $RTIME
		;;
	restart)
		echo "Restarting service"
		$0 stop
		$0 start
		;;
	*)
		echo "Invalid command. Usage: /etc/init.d/pi-sensor-service {start|stop|restart}"
		exit 1
		;;
esac
exit 0

